name: test

# PR作成時、コミットプッシュ時にワークフローを実行
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

# すべてのアクセス許可を無効に設定
permissions: {}

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      # プロジェクトのチェックアウト(ジョブ毎に実行必須)
      - name: checkout project
        # @vXのようなバージョン指定にすると、最新バージョンでセキュリティ的に問題があるアクションを意図せず使用してしまう可能性がある
        # よって@vX.Y.Zにすればリスクは軽減するが、それでもバージョンは自由に作り直せるのでより厳密にコミットハッシュを指定
        # v4.2.2 ref. https://github.com/actions/checkout/releases/tag/v4.2.2
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: bind and deploy
        uses: ./.github/actions/build-deploy
        with:
          project_id: ${{ secrets.TEST_PROJECT_ID }}
          project_number: ${{ secrets.TEST_PROJECT_NUMBER }}
          bucket_uri: gs://${{ secrets.TEST_BUCKET_NAME }}
          workload_identity_provider: ${{ secrets.TEST_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.TEST_SERVICE_ACCOUNT }}
          test_run: true
          components_image_version: ${{ github.sha }}

  slack:
    if: always()
    runs-on: ubuntu-22.04
    needs: build-deploy
    permissions:
      contents: read
    steps:
      - name: checkout project
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      # ワークフローの実行結果をSlackの指定したチャネルに通知
      - name: send the workflow result to the slack channel
        uses: ./.github/actions/slack
        with:
          conclusion: ${{ needs.build-deploy.result }}
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
